In [1]:
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import tensorflow as tf
# from tensorflow.python.keras.utils.np_utils import to_categorical
from keras.utils import to_categorical
import model

In [2]:
#read dataset
df = pd.read_csv('./data/c4_game_database.csv', sep=',',header=0)
df.head(10)

pos_01  pos_02  pos_03  pos_04  pos_05  pos_06  pos_07  pos_08  pos_09  \
0     1.0     1.0     1.0    -1.0    -1.0     1.0     0.0    -1.0    -1.0   
1     0.0     0.0     1.0     1.0     1.0     1.0     0.0     0.0     0.0   
2     0.0     1.0     0.0     1.0     0.0     0.0     0.0     0.0    -1.0   
3     0.0     0.0     0.0     1.0     0.0     0.0     0.0     0.0     0.0   
4     0.0    -1.0    -1.0    -1.0     1.0     0.0     0.0     1.0     1.0   
5     0.0     0.0     0.0     0.0     0.0     0.0     1.0     0.0     0.0   
6     0.0     0.0     1.0     1.0     1.0     1.0     0.0     0.0     0.0   
7     0.0     0.0     0.0     0.0     1.0    -1.0     0.0     0.0    -1.0   
8     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
9     0.0     0.0     1.0     0.0     0.0     0.0     0.0     0.0    -1.0   

   pos_10  ...  pos_34  pos_35  pos_36  pos_37  pos_38  pos_39  pos_40  \
0    -1.0  ...     1.0     1.0    -1.0     1.0    -1.0     1.0    -1.0   
1     1.0  ...    -1.0     1.0     1.0    -1.0    -1.0    -1.0     1.0   
2     0.0  ...     0.0    -1.0     1.0    -1.0    -1.0     1.0    -1.0   
3     0.0  ...     0.0     1.0     1.0     1.0    -1.0     1.0    -1.0   
4     1.0  ...     0.0     1.0    -1.0    -1.0     1.0    -1.0     1.0   
5    -1.0  ...    -1.0     1.0    -1.0     1.0    -1.0     1.0    -1.0   
6    -1.0  ...     1.0     0.0    -1.0     1.0    -1.0    -1.0     1.0   
7     0.0  ...     1.0     1.0     1.0    -1.0     0.0     1.0    -1.0   
8     1.0  ...    -1.0     0.0     1.0    -1.0     1.0    -1.0     1.0   
9    -1.0  ...     1.0     1.0    -1.0     1.0    -1.0    -1.0     1.0   

   pos_41  pos_42  winner  
0     1.0    -1.0    -1.0  
1     1.0    -1.0     1.0  
2    -1.0    -1.0    -1.0  
3     0.0     1.0    -1.0  
4     0.0    -1.0     1.0  
5    -1.0     1.0     1.0  
6    -1.0    -1.0     1.0  
7     1.0     1.0     1.0  
8    -1.0    -1.0    -1.0  
9    -1.0     1.0     1.0  

[10 rows x 43 columns]

In [6]:
df = df.dropna()
y = df['winner']
x = df.drop('winner', axis=1)

In [7]:
x.head(10)

pos_01  pos_02  pos_03  pos_04  pos_05  pos_06  pos_07  pos_08  pos_09  \
0     1.0     1.0     1.0    -1.0    -1.0     1.0     0.0    -1.0    -1.0   
1     0.0     0.0     1.0     1.0     1.0     1.0     0.0     0.0     0.0   
2     0.0     1.0     0.0     1.0     0.0     0.0     0.0     0.0    -1.0   
3     0.0     0.0     0.0     1.0     0.0     0.0     0.0     0.0     0.0   
4     0.0    -1.0    -1.0    -1.0     1.0     0.0     0.0     1.0     1.0   
5     0.0     0.0     0.0     0.0     0.0     0.0     1.0     0.0     0.0   
6     0.0     0.0     1.0     1.0     1.0     1.0     0.0     0.0     0.0   
7     0.0     0.0     0.0     0.0     1.0    -1.0     0.0     0.0    -1.0   
8     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
9     0.0     0.0     1.0     0.0     0.0     0.0     0.0     0.0    -1.0   

   pos_10  ...  pos_33  pos_34  pos_35  pos_36  pos_37  pos_38  pos_39  \
0    -1.0  ...     1.0     1.0     1.0    -1.0     1.0    -1.0     1.0   
1     1.0  ...    -1.0    -1.0     1.0     1.0    -1.0    -1.0    -1.0   
2     0.0  ...    -1.0     0.0    -1.0     1.0    -1.0    -1.0     1.0   
3     0.0  ...     0.0     0.0     1.0     1.0     1.0    -1.0     1.0   
4     1.0  ...     1.0     0.0     1.0    -1.0    -1.0     1.0    -1.0   
5    -1.0  ...    -1.0    -1.0     1.0    -1.0     1.0    -1.0     1.0   
6    -1.0  ...    -1.0     1.0     0.0    -1.0     1.0    -1.0    -1.0   
7     0.0  ...    -1.0     1.0     1.0     1.0    -1.0     0.0     1.0   
8     1.0  ...     1.0    -1.0     0.0     1.0    -1.0     1.0    -1.0   
9    -1.0  ...     1.0     1.0     1.0    -1.0     1.0    -1.0    -1.0   

   pos_40  pos_41  pos_42  
0    -1.0     1.0    -1.0  
1     1.0     1.0    -1.0  
2    -1.0    -1.0    -1.0  
3    -1.0     0.0     1.0  
4     1.0     0.0    -1.0  
5    -1.0    -1.0     1.0  
6     1.0    -1.0    -1.0  
7    -1.0     1.0     1.0  
8     1.0    -1.0    -1.0  
9     1.0    -1.0     1.0  

[10 rows x 42 columns]

In [8]:
# X_train = np.array(X_train).reshape((-1, 42))
# X_test = np.array(X_test).reshape((-1, 42))

x = np.array(x)
y = to_categorical(np.array(y), 3)

In [9]:
print(x.shape)
print(y.shape)

(376619, 42)
(376619, 3)


In [10]:
X_train, X_test, y_train, y_test = train_test_split(x, y, 
test_size=0.2, random_state=0)

In [11]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(301295, 42)
(75324, 42)
(301295, 3)
(75324, 3)


In [12]:
print(y_test)

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [13]:
import model

In [14]:
# BATCH_SIZE = 20
# STEPS_PER_EPOCH = train_labels.size / BATCH_SIZE
# SAVE_PERIOD = 10

# # Create a callback that saves the model's weights every 10 epochs
# cp_callback = tf.keras.callbacks.ModelCheckpoint(
#     filepath=checkpoint_path, 
#     verbose=1, 
#     save_weights_only=True,
#     save_freq= int(SAVE_PERIOD * STEPS_PER_EPOCH))

# # Train the model with the new callback
# model.fit(train_images, 
#           train_labels,
#           batch_size=BATCH_SIZE,
#           steps_per_epoch=STEPS_PER_EPOCH,
#           epochs=50, 
#           callbacks=[cp_callback],
#           validation_data=(test_images,test_labels),
#           verbose=0)

In [15]:
cp_callback = tf.keras.callbacks.ModelCheckpoint(filepath = './checkpoints', verbose = 1, save_freq = 'epoch', period = 50)

In [16]:
model = model.getModel()

nEpochs = 300
batchSize = 50

history = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=nEpochs, batch_size=batchSize, callbacks=[cp_callback])
model.save('./models3')


Epoch 1/300
6026/6026 [==============================] - 20s 3ms/step - loss: 0.3366 - acc: 0.8525 - val_loss: 0.0835 - val_acc: 0.9682
Epoch 2/300
6026/6026 [==============================] - 20s 3ms/step - loss: 0.0733 - acc: 0.9729 - val_loss: 0.0539 - val_acc: 0.9805
Epoch 3/300
6026/6026 [==============================] - 21s 3ms/step - loss: 0.0472 - acc: 0.9837 - val_loss: 0.0470 - val_acc: 0.9835
Epoch 4/300
6026/6026 [==============================] - 21s 3ms/step - loss: 0.0354 - acc: 0.9880 - val_loss: 0.0283 - val_acc: 0.9897
Epoch 5/300
6026/6026 [==============================] - 20s 3ms/step - loss: 0.0271 - acc: 0.9907 - val_loss: 0.0282 - val_acc: 0.9898
Epoch 6/300
6026/6026 [==============================] - 21s 3ms/step - loss: 0.0211 - acc: 0.9931 - val_loss: 0.0253 - val_acc: 0.9912
Epoch 7/300
6026/6026 [==============================] - 20s 3ms/step - loss: 0.0166 - acc: 0.9944 - val_loss: 0.0246 - val_acc: 0.9916
Epoch 8/300
6026/6026 [=========================

6026/6026 [==============================] - 18s 3ms/step - loss: 0.0033 - acc: 0.9993 - val_loss: 0.0133 - val_acc: 0.9975
Epoch 61/300
6026/6026 [==============================] - 19s 3ms/step - loss: 0.0043 - acc: 0.9991 - val_loss: 0.0147 - val_acc: 0.9982
Epoch 62/300
6026/6026 [==============================] - 20s 3ms/step - loss: 0.0032 - acc: 0.9993 - val_loss: 0.0153 - val_acc: 0.9969
Epoch 63/300
6026/6026 [==============================] - 22s 4ms/step - loss: 0.0035 - acc: 0.9992 - val_loss: 0.0142 - val_acc: 0.9975
Epoch 64/300
6026/6026 [==============================] - 25s 4ms/step - loss: 0.0034 - acc: 0.9992 - val_loss: 0.0184 - val_acc: 0.9969
Epoch 65/300
6026/6026 [==============================] - 20s 3ms/step - loss: 0.0054 - acc: 0.9989 - val_loss: 0.0168 - val_acc: 0.9970
Epoch 66/300
6026/6026 [==============================] - 19s 3ms/step - loss: 0.0037 - acc: 0.9992 - val_loss: 0.0173 - val_acc: 0.9967
Epoch 67/300
6026/6026 [==============================

KeyboardInterrupt: 

In [18]:
import keras
loadmodel = keras.models.load_model('./checkpoints')

In [19]:
loadmodel.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 512)               22016     
_________________________________________________________________
dense_1 (Dense)              (None, 256)               131328    
_________________________________________________________________
dense_2 (Dense)              (None, 128)               32896     
_________________________________________________________________
dense_3 (Dense)              (None, 50)                6450      
_________________________________________________________________
dropout (Dropout)            (None, 50)                0         
_________________________________________________________________
dense_4 (Dense)              (None, 25)                1275      
_________________________________________________________________
dropout_1 (Dropout)          (None, 25)                0

In [78]:
def drawBoard(board):
    nboard = [ [0.0]* 7 for i in range(6)]
    for i in range(6):
        for j in range(7):
            if board[i][j] == 1.0:
                nboard[i][j] = 'X'
            if board[i][j] == -1.0:
                nboard[i][j] = 'O'
            if board[i][j] == 0.0:
                nboard[i][j] = ' '
    return nboard

In [94]:
test = X_test[6]
print(test)
# test = np.array([1.0,1.0,1.0,-1.0,-1.0,1.0,0.0,-1.0,-1.0,-1.0,1.0,-1.0,-1.0,0.0,-1.0,1.0,1.0,-1.0,1.0,1.0,0.0,1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,1.0,1.0,-1.0,-1.0,1.0,1.0,1.0,-1.0,1.0,-1.0,1.0,-1.0,1.0,-1.0])

[0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
 0.000 0.000 0.000 0.000 0.000 -1.000 0.000 1.000 0.000 0.000 0.000 0.000
 -1.000 1.000 -1.000 0.000 0.000 0.000 0.000 1.000 -1.000 1.000 0.000
 0.000 -1.000 1.000 1.000 1.000 -1.000 0.000]


In [95]:
test = test.reshape((-1,42))

In [96]:
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

In [97]:
print(test.shape)

(1, 42)


In [98]:
test1 = test.reshape((6, 7))
test1 = drawBoard(test1)
test1

[[' ', ' ', ' ', ' ', ' ', ' ', ' '],
 [' ', ' ', ' ', ' ', ' ', ' ', ' '],
 [' ', ' ', ' ', 'O', ' ', 'X', ' '],
 [' ', ' ', ' ', 'O', 'X', 'O', ' '],
 [' ', ' ', ' ', 'X', 'O', 'X', ' '],
 [' ', 'O', 'X', 'X', 'X', 'O', ' ']]

In [99]:
# test = ['']
# loadmodel.evaluate(X_test, y_test)
result = loadmodel.predict(test)
print(result)

[[0.000 1.000 0.000]]


In [63]:
class_vector =[-1, 0, 1, 0, 1, -1]
print(class_vector)
  
# Applying the function on input class vector
from keras.utils import to_categorical
output_matrix = to_categorical(class_vector, 3)
  
print(output_matrix)

[-1, 0, 1, 0, 1, -1]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [67]:
class_vector =[0, 1, -1]
print(class_vector)
  
# Applying the function on input class vector
from keras.utils import to_categorical
output_matrix = to_categorical(class_vector, 3)
  
print(output_matrix)

[0, 1, -1]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
